default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Root@123
  host: localhost
  port: 3306
  database: foodie

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
